const dataText = {
  "en": {
    global_back: "Back",
    global_select: "Enter",
    global_ok: "OK",
    global_games: "Games",
    global_no_games: "No Games",
    global_all: "All",
    global_title: "Title",
    global_menu: "Menu",
    global_view: "View",
    global_noFavorites: "No favorites set",
    global_favorite: "Favorites",
    home_system: "system",
    home_collection: "collection",
    home_favorite: "favorite",
    home_recent: "recent",
    games_play: "Start",
    games_info: "Details",
    games_select: "Select",
    games_favorite: "Add to favorite",
    games_favorite_cancel: "Remove from favorite",
    games_more: "More",
    sort_by: "By ",
    sort_title: "By Title",
    sort_last_played: "By Last Played",
    sort_rating: "By Rating",
    sort_release_year: "By Release Year",
    sort_show_all: "Show All",
    sort_favorites_only: "Favorites Only",
    sort_play_time: "By Play Time",
    sort_play_count: "By Play Count",
  },
  "cn": {
    global_back: "返回",
    global_select: "确定",
    global_games: "游戏",
    global_no_games: "无游戏",
    global_all: "全部",
    global_title: "标题",
    global_menu: "菜单",
    global_view: "视图",
    global_favorite: "收藏",
    home_system: "机型",
    home_collection: "合集",
    home_favorite: "收藏",
    home_recent: "最近",
    games_play: "开始",
    games_info: "详情",
    games_select: "选择",
    games_favorite: "添加收藏",
    games_favorite_cancel: "取消收藏",
    games_more: "更多",
    sort_by: "按",
    sort_title: "按标题",
    sort_last_played: "按最后游玩",
    sort_rating: "按评分",
    sort_release_year: "按发售时间",
    sort_show_all: "显示全部",
    sort_favorites_only: "仅显示收藏",
    sort_play_time: "按游玩时长",
    sort_play_count: "按游玩次数"
  }
}

const theme = {
  "background": "#F3F3F3",
  "text": "#70000000",
  "title": "#444",
  "background_dark": "#333333",
  "text_dark": "#DDD",
  "title_dark": "#DDD",
//  "background_grid": "#283593",
  "background_grid": "#222",
  "gridColumnCount": 5,
  "gridLargeColumnCount": 3,
  "primaryColor": "#1565C0"
}

const systemColors = {
  "nes": "#920E00",
  "n64": "#920E00",
  "nds": "#920E00",
  "famicom": "#920E00",
  "gb": "#920E00",
  "gba": "#920E00",
  "gbc1": "#920E00",
  "gbc": "#920E00",
  "snes": "#AA6AFF",
  "sfc": "#920E00",
  "gg": "#2196F3",
  "gamegear": "#2196F3",
  "mastersystem": "#2196F3",
  "genesis": "#2196F3",
  "megadrive": "#2196F3",
  "saturn": "#2196F3",
  "sega32x": "#2196F3",
  "segacd": "#2196F3",
  "dreamcast": "#2196F3",
  "psp": "#616161",
  "psx": "#616161",
  "ps2": "#616161",
  "neogeo": "#0277BD",
  "ngp": "#689F38",
  "ngpc": "#689F38",
  "neogeocd": "#689F38",
  "android": "#5BFF92",
  "pcengine": "#FF7043",
  "tg16": "#FF7043",
  "cps": "#ECAF00",
  "cps1": "#ECAF00",
  "cps2": "#ECAF00",
  "cps3": "#ECAF00",
  "mame": "#546E7A",
  "naomi": "#BF360C",
  "wonderswan": "#6A1B9A",
  "wonderswancolor": "#6A1B9A",
  "pgm": "#00838F",

  "kof": "#1A237E",
  "mslug": "#777",
  "megaman": "#2154D1",
  "sf": "#CB1321",
  "samsho": "#204A2C",
  "castlevania": "#6c3122",
  "zelda": "#FBC02D",
  "finalfantasy": "#222222",
  "metroid": "#0a7f9a",

  "default": "#2387FF"
}

const systemCompanies = {
  "dreamcast": "Sega",
  "gg": "Sega",
  "gamegear": "Sega",
  "genesis": "Sega",
  "megadrive": "Sega",
  "saturn": "Sega",
  "segacd": "Sega",
  "megacd": "Sega",
  "mastersystem": "Sega",
  "naomi": "Sega",
  "sega32x": "Sega",
  "neogeo": "SNK",
  "neogeocd": "SNK",
  "ngp": "SNK",
  "ngpc": "SNK",
  "famicom": "Nintendo",
  "gb": "Nintendo",
  "gba": "Nintendo",
  "gbc": "Nintendo",
  "snes": "Nintendo",
  "nes": "Nintendo",
  "sfc": "Nintendo",
  "n64": "Nintendo",
  "nds": "Nintendo",
  "pcengine": "NEC",
  "tg16": "NEC",
  "psx": "Sony",
  "psp": "Sony",
  "ps2": "Sony",
  "wonderswan": "Bandai",
  "wonderswancolor": "Bandai",
  "cps": "capcom",
  "cps1": "capcom",
  "cps2": "capcom",
  "cps3": "capcom",
  "pgm": "igs",
  "mame": "arcade",

  "kof": "snk",
  "mslug": "snk",
  "megaman": "capcom"
}
